# Schema for the configuration files of the Extra Body Classes module.

extra_body_classes.settings:
  type: config_object
  label: 'extra body classes settings'
  mapping:
    extra_body_classes_date:
      type: integer
      label: 'date'
    extra_body_classes_year:
      type: integer
      label: 'year'
    extra_body_classes_month:
      type: integer
      label: 'month'
    extra_body_classes_day:
      type: integer
      label: 'day'
    extra_body_classes_roles:
      type: integer
      label: 'Current user roles'
    extra_body_classes_browser_single_day_event:
      type: string
      label: 'Add single day event class'
    extra_body_classes_browser_single_day_event_begins:
      type: integer
      label: 'Add single day event date'
    extra_body_classes_event:
      type: string
      label: 'Add multiple day event'
    extra_body_classes_event_start_date:
      type: string
      label: 'Add multiple day event class'
    extra_body_classes_event_end_date:
      type: string
      label: 'Add multiple day event class'
    extra_body_classes_custom_classes:
      type: string
      label: 'Add custom classes'
    extra_body_classes_custom_classes_path:
      type: string
      label: 'Add custom classes path'
